<?php
  define("SERVER","db");
  define("USER","root");
  define("PASS","test");
  define("BD","veris");
  define("PATH_pacientes","../../imagenes/Usuarios/");
  define("PATH_medicos","../../imagenes/Sellos/");
  define("PATH_administrador","../../imagenes/paises/");
 ?>